### ISSUE TITLE
投稿失敗時のフラッシュメッセージ

### ISSUE THREAD

**Issue by shogo0625** [kyoukono/blog_friends#86]
何も記入せず投稿→flashで「今日のところはこのへんで」の記入を促される→
本文に「今日のところはこのへんで」を含めて、題名は空欄のまま投稿→再度同じflashが表示される
flash => flash.now で解消されると思われます。

**Comment by hikaru9507** [comment]
ありがとうございます。直しました。次回更新時には本番環境でも直っていると思います。
